name: flutter_scrapper_example
description: Example app demonstrating flutter_scrapper usage
version: 1.0.0+1

environment:
  sdk: ^3.0.0
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # For local development and testing - uncomment when developing
  flutter_scrapper:
    path: ../
  # For published package
  # flutter_scrapper: ^0.1.0
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true 